# Generated by Django 2.0.7 on 2019-10-31 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodtype', models.CharField(max_length=50)),
                ('volume', models.FloatField()),
                ('takendate', models.DateField(verbose_name='blood taken date')),
                ('expdate', models.DateField(verbose_name='blood expire date')),
                ('donor', models.CharField(max_length=50)),
                ('disposeddate', models.DateField(null=True, verbose_name='blood disposed date')),
                ('isTested', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingaddress', models.CharField(max_length=100, null=True)),
                ('bookDate', models.DateTimeField(verbose_name='booking date')),
                ('volume', models.FloatField()),
                ('userBooked', models.CharField(max_length=50, null=True)),
                ('blood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodprofile.Blood')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodType', models.CharField(max_length=50)),
                ('rsvVolume', models.FloatField()),
                ('userReserved', models.CharField(default='', max_length=50, null=True)),
                ('rsvDate', models.DateField(verbose_name='reserve blood date')),
                ('address', models.CharField(default='', max_length=60, null=True)),
            ],
        ),
    ]
