# Generated by Django 2.2.6 on 2019-11-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodprofile', '0002_remove_book_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood',
            name='disposeddate',
        ),
        migrations.AddField(
            model_name='blood',
            name='isBooked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blood',
            name='isTested',
            field=models.BooleanField(default=False),
        ),
    ]
